# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sfR1r7FAzZfI0LhtA2s0s-7MHFDysSIR
"""

身高=float(input())
體重=float(input())
bmi=體重/(身高**2)
print(bmi)